#!/bin/bash
yum install -y httpd24 php70 mysql56-server php70-mysqlnd php70-mbstring
sudo service httpd start
yum install curl
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer